name: Docker

on:
    workflow_call:

jobs:
  docker:   #-----------------------------------[   JOB 1 ]--------------------------------------------------#
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}        

# Docker Build and Push code (V6.7.0) from marketplace by Docker 

      - name: my-postgres - Build and push Docker image
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85
        uses: docker/build-push-action@v6.7.0
        with:
          # Build's context is the set of files located in the specified PATH or URL
          context: .

          # Path to the Dockerfile
          file: ./Dockerfile

          # List of metadata for an image
          #labels: # optional

          # Push is a shorthand for --output=type=registry
          push: true

          # List of tags - marcando dinamicamente com a branch atual depois dos : ref_name
          tags: brunojose1977/my-postgres:${{github.ref_name}}

                
# Códigos antigos

#      - name: Install Docker Compose
#        run: |
#            sudo apt-get update
#            sudo apt-get install docker-compose         
#         
#      - name: docker-compose build
#        run: docker-compose build

