name: Entrega Continua

on:
    workflow_call:

jobs:

    EC2:    #-----------------------------------[   JOB 1 ]--------------------------------------------------#
        runs-on: ubuntu-latest
        steps:
        - name: Download a Build Artifact
          uses: actions/download-artifact@v3.0.0
          with:
            name: programa
        - uses: actions/checkout@v3
        - name: Deploy to Staging server
        - name: Deploy to Server
          uses: easingthemes/ssh-deploy@main
          with:
              SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
              REMOTE_USER: ${{ secrets.REMOTE_USER }}
              TARGET: ${{ secrets.REMOTE_TARGET }}
              EXCLUDE: "/dist/, /node_modules/"    
              
